spring:
  application:
    name: auth-service
  config:
    import:
      - application-security.yml
      - application-db.yml
      - application-eureka-client.yml

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        generate-ddl: true
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50
      open-in-view: false

server:
  port: 9002
#  port: 0

logging:
  level:
    com.auth.authservice.api: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh, info, metrics, prometheus

