spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters: # 모든 서비스에 적용되는 default-filter
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - name: LoggingFilter
          args:
            preLogger: true
            postLogger: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:8081' # front-app url
            allow-credentials: true # JWT 나 쿠키를 사용해 메시지를 보내야 할 경우 true
            allowedHeaders: '*'
            allowedMethods: # 전체 메서드 명시
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
              - PATCH
            exposed-headers:
              - Authorization
              - Refresh-Token
            max-age: 3600

      
      routes: # predicates 에 매칭되는 uri, filter 정의
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /member/**
          filters:
            - JwtValidationCheckFilter

        - id: ediary-diary
          uri: lb://EDIARY-DIARY
          predicates:
            - Path=/diary/**
          filters:
            - RemoveRequestHeader=Cookie
            #            - RewritePath=/diary/(?<segment>.*), /$\{segment}
            - RewritePath=/diary(?:/(?<segment>.*))?, /$\{segment}
            - JwtValidationCheckFilter

        - id: ediary-point
          uri: lb://EDIARY-POINT
          predicates:
            - Path=/point/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/point(?:/(?<segment>.*))?, /$\{segment}
            - JwtValidationCheckFilter
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9761/eureka

server:
  port: 9001

jwt:
  secret-key: f4f0d91f787470f05eba631f1bac031bb95424497666984ee7cc9b73bab1604c

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, metrics, prometheus