spring:
  application:
    name: discovery
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: ecommerce

server:
  port: 9761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/