security:
  oauth2:
    client:
      registration:
        google:
          client-id: 261020695754-1hare0k9ja82imlmlr07pnkb8oequ3dl.apps.googleusercontent.com
          client-secret: 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
          scope:
            - openid
            - profile
            - email

        naver:
          client-id: 86F6bsUgZ5NHu11Jh5Zt
          client-secret: 1sGx7H05bv
          client-name: naver-client-app
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:9001/login/oauth2/code/naver
          scope:
            - profile
            - email

        kakao:
          client-id: 2b5d0b45201da6cfb3f2862ad0d384e3
          client-secret: iN4z9pgrkd6uUxIbbojMvWADqlQf4Ew4
          client-name: kko-client-app-TEST
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:9001/login/oauth2/code/kakao
          client-authentication-method: client_secret_post
          scope:
            - profile_nickname
            - profile_image
            - account_email
            - name
            - openid

      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response

        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
          user-info-uri: https://kapi.kakao.com//v2/user/me
          user-name-attribute: sub

jwt:
  header: Authorization
  refresh-token-header: Refresh-Token
  iss: localhost:9001
  secret-key: f4f0d91f787470f05eba631f1bac031bb95424497666984ee7cc9b73bab1604c