FROM openjdk:17-ea-slim
VOLUME /tmp
COPY build/libs/emotion-diary-point-0.0.1-SNAPSHOT.jar emotion-diary-point-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "emotion-diary-point-0.0.1-SNAPSHOT.jar"]
